Parameters: 
  myKeyPair: 
    Description: Amazon EC2 Key Pair
    Type: "AWS::EC2::KeyPair::KeyName"
  NetworkStackNameParameter:
    Type: String
    Default: "virtual-network"

Resources:

  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.small
      SecurityGroupIds:
          - Fn::ImportValue: !Sub "${NetworkStackNameParameter}-SecurityGroupIds"
      AvailabilityZone: "eu-west-2a" 
      ImageId: ami-084e8c05825742534
      KeyName: !Ref myKeyPair
      SubnetId: 
        Fn::ImportValue: !Sub "${NetworkStackNameParameter}-PublicSubnet"
      UserData:
        Fn::Base64:
          !Sub |
             #!/bin/bash
             sudo yum update -y
             sudo amazon-linux-extras install php8.0 mariadb10.5
             sudo yum install -y httpd
             sudo systemctl enable httpd
             sudo usermod -a -G apache ec2-user
             sudo chown -R ec2-user:apache /var/www
             sudo chmod 2775 /var/www
             find /var/www -type d -exec sudo chmod 2775 {} \;
             find /var/www -type f -exec sudo chmod 0664 {} \;
             pwd
             date
             ls -la

  ElasticIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: VPC
      InstanceId: !Ref Ec2Instance