Parameters: 
  myKeyPair: 
    Description: Amazon EC2 Key Pair
    Type: "AWS::EC2::KeyPair::KeyName"

Resources:

  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.small
      SecurityGroupIds:
        - Fn::ImportValue: !Sub myamalia-SecurityGroupIds
          
      AvailabilityZone: "eu-west-2a" 
      ImageId: ami-084e8c05825742534
      KeyName: !Ref myKeyPair
      SubnetId: subnet-0c78ac5f81ffeb051
#        Ref: "PublicSubnet"
      UserData:
        Fn::Base64:
          !Sub |
             #!/bin/bash
             # Install the Docker Engine Container Runtime 
             sudo apt-get update
             sudo apt-get install ca-certificates curl gnupg lsb-release 
             sudo mkdir -p /etc/apt/keyrings
             curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
             echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
             sudo apt-get update
             sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin

  ElasticIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: VPC
      InstanceId: !Ref Ec2Instance