on: 
  push:
    branches:
    - main
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::423261455848:role/my-github-actions-role-test
        aws-region: eu-west-2

    - name: run a AWS CLI command
      run: |
        aws cloudformation create-stack --stack-name virtual-network --template-body file://virtual-network.yaml






     
              