name: "Deploy CloudFormation Stack"
on: 
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: MGenteluci/cloudformation-deploy-action@v1.4.1
      env:
        TEMPLATE: 'virtual-network.yml'
        AWS_STACK_NAME: 'virtual-network'
        AWS_REGION: 'eu-west-2'
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      run:
        aws --version
        aws cloudformation create-stack --stack-name virtual-network --template-body file://virtual-network.yaml
        aws cloudformation create-stack --stack-name instance --template-body file://instance.yaml --parameters ParameterKey=myKeyPair,ParameterValue=website
              